name: List Changed Files
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files
      id: getfile
      run: |
        echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD)"

    - name: Use file list
      run: |
        FILES="${{ steps.getfile.outputs.files }}"
        echo "File list: $FILES"
        
    - name: Print changed files
      run: |
        echo "Changed files in last commit:"
        echo "${{ steps.getfile.outputs.files }}"
