name: List Changed Files
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files
      id: getfile
      run: |
        declare -A env_vars=( ["ddev"]="d1" ["dcons1"]="i1" ["ddev2"]="d2" ["dcons2"]="i2" ["ddev3"]="d3" ["ddev4"]="d4" ["dprod1"]="p1" )
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files: $CHANGED_FILES"
        for key in ${!env_vars[@]}; do
          if [[ $CHANGED_FILES == *"fkhistory/fdcc/$key"* ]]; then
            echo "Setting environment variable $key to ${env_vars[$key]}"
            echo "$key=${env_vars[$key]}" >> $GITHUB_ENV
            queryParams+="&$key=${env_vars[$key]}"
          fi
        done
        echo "queryParams=${queryParams:1}"