name: List Changed Files
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files
      id: getfile
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files: $CHANGED_FILES"
        if [[ $CHANGED_FILES == *"fkhistory/fdcc"* ]]; then
          echo "OK"
        else
          echo "Not OK"
        fi