name: List Changed Files
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files
      id: getfile
      run: |
        declare -A env_vars=( ["DEV1"]="d1" ["CONS1"]="i1" ["DEV2"]="d2" ["CON2"]="i2" ["DEV3"]="d3" ["DEV4"]="d4" ["DPROD1"]="p1" )
        CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
        echo "Changed files: $CHANGED_FILES"
        for key in ${!env_vars[@]}; do
          echo "Checking for $key in $CHANGED_FILES"
          if [[ $CHANGED_FILES == *"fkhistory/fdcc/$key"* ]]; then
            echo "Setting environment variable $key to ${env_vars[$key]}"
            echo "$key=${env_vars[$key]}" >> $GITHUB_ENV
          fi
        done