name: Get Changed Files

on:
  push:
    branches:
      - main

jobs:
  get_changed_files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Get Changed Files
      id: changed_files
      run: |
        CHANGED_FILES=$(git diff --name-only ${{ github.sha }}^ ${{ github.sha }})
        echo "::set-output name=changed_files::${CHANGED_FILES}"

    - name: Display Changed Files
      run: |
        echo "Changed files: ${{ steps.changed_files.outputs.changed_files }}"
